rappmanager:
  csarlocation: src/main/resources/csar
  acm:
    baseurl: http://10.101.2.254:30442/onap/policy/clamp/acm/v2/
    username: runtimeUser
    password: zb!XztG34
    compositionDefinitionLocation: src/main/resources/compositiondefinition.json
    maxRetries: 3
    retryInterval: 2 #seconds
  sme:
    baseurl: http://10.101.2.254:30232
    providerBasePath: /api-provider-management/v1/
    invokerBasePath: /api-invoker-management/v1/
    publishApiBasePath: /published-apis/v1/
    maxRetries: 3
    retryInterval: 2 #seconds

logging:
  level:
    root: INFO
    com.oransc.rapps: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG
    org.springframework.web.client.RestTemplate: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"