@startuml
participant "rApp Manager"
participant "ACM Runtime"
participant "CAPIF"

autonumber

group Application Startup
"rApp Manager"->"CAPIF": Create "rApp Manager" as AMF
end

autonumber

group Application Stop
"rApp Manager"->"CAPIF": Delete "rApp Manager" as AMF
end

@enduml